title: image grid
author: author
email: your-email@example.com
description: A simple image grid theme. Add your site description here in the _config.yml file. It will appear in your document head meta (for
  Google search results).

# generate social links in footer
social_links:
  twitter: jekyll
  github: jekyll
  # facebook: jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

# settings for image grid homepage
grid_settings:
  show_all_images: true #true - displays all images in grid page, false - only show first (file name of image sorted alphabetically) image of post in grid page
  display: square-cropped #square-cropped - images displayed in square grid and cropped, #square-og - images displayed in square grid and with original aspect ratio, masonry - images displayed in original aspect ratio but staggered (please note this will display the images in top to bottom order instead of left to right)

# settings for post pages
post_settings:
  show_title: true #true - shows title of post (post filename or title in front matter of post file), false - does not show title of post. this settings can be overwritten in the frontmatter of individual post files with the show_title variable.
  show_date: true #true - shows date of post (from post filename), false - does not show date of post

plugins:
  - jekyll-seo-tag

include:
  - _images
