title: image grid
author: author
email: your-email@example.com
description: A simple image grid theme. Add your site description here in the _config.yml file. It will appear in your document head meta (for
  Google search results).

# generate social links in footer
social_links:
  twitter: jekyllrb
  github:  jekyll
  # facebook: jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon

  # Mastodon instances
  # mastodon:
  # - username: jekyll
  #   instance: example.com
  # - username: jekyll2
  #   instance: example.com

plugins:
  - jekyll-seo-tag